#原mod版本
updateGameVersionFrom = "1.21.5"
#新mod版本
updateGameVersionTo = "1.21.5"
#原mod目录
modFolderFrom = "./tests/mods"
#新mod目录
modFolderTo = "./tests/newMods"
#备份目录
backupFolder = "./tests/backup"
#缓存目录
cacheFolder = "./.cache"
#更新来源
update_from = "Modrinth"
#最大重试次数
maxRetries = 5
